db_obj.delete_tables()
print("<------------THE TABLES HAVE BEEN DROPPED------------->")
print("<------------CREATING THE TABLES---------->")
db_obj.create_tables()
print("<-------------THE TABLES HAVE BEEN CREATED-------------->")
